# tasks file for 6533
- name: resoconto in file {{ logfile }}
  shell: echo "Applicato il bug {{bug}} dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
  delegate_to: localhost
  changed_when: false
- name: resoconto in database ansible
  shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
  delegate_to: localhost
  changed_when: false

- name: esiste il file /var/www/html/dl/_header.php
  stat: path=/var/www/html/dl/_header.php
  register: fileok_6533

- block:
  - name: copio il nuovo file _header.php
    copy:
        backup: true
        src: files/_header.php
        dest: /var/www/html/dl/_header.php
        owner: apache
        group: apache
        mode: 0774
  - name: posiziono il file del logo Enghouse
    copy:
        src: files/EnghouseLogo.png
        dest: /var/www/html/dl/img
        owner: apache
        group: apache
        mode: 0774
  when: fileok_6533.stat.exists
